package com.cloudmall.product;
import com.cloudmall.common.api.*; import com.cloudmall.common.error.*; import org.springframework.web.bind.annotation.*; import javax.validation.Valid; import javax.validation.constraints.*; import java.math.*; import java.util.*; import java.util.concurrent.*;
@RestController @RequestMapping("/api") public class ProductController{static final Map<Long,Product> DATA=new ConcurrentHashMap<>();static final Map<Long,Category> CATS=new ConcurrentHashMap<>();static{DATA.put(1L,new Product(1L,"CloudMall Demo","99.00",true));}
 @GetMapping("/categories") public ApiResponse<?> cats(){return ApiResponse.ok(CATS.values());} @PostMapping("/categories") public ApiResponse<?> addCat(@RequestBody Category c){c.id=(long)(CATS.size()+1);CATS.put(c.id,c);return ApiResponse.ok(c);}
 @GetMapping("/products") public ApiResponse<?> list(@RequestParam(required=false)String keyword,@RequestParam(required=false)Boolean status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize){List<Product> x=new ArrayList<>();for(Product p:DATA.values())if((keyword==null||p.name.contains(keyword))&&(status==null||p.published==status))x.add(p);return ApiResponse.ok(new PageResult<>(x,page,pageSize,x.size()));}
 @GetMapping("/products/{id}") public ApiResponse<?> get(@PathVariable Long id){Product p=DATA.get(id);if(p==null)throw new BizException(ErrorCodes.NOT_FOUND,"商品不存在",404);return ApiResponse.ok(p);}
 @PostMapping("/products") public ApiResponse<?> create(@Valid @RequestBody Product p){p.id=(long)(DATA.size()+1);DATA.put(p.id,p);return ApiResponse.ok(p);} @PutMapping("/products/{id}") public ApiResponse<?> update(@PathVariable Long id,@RequestBody Product p){Product old=DATA.get(id);if(old==null)throw new BizException(ErrorCodes.NOT_FOUND,"商品不存在",404);old.name=p.name;old.price=p.price;return ApiResponse.ok(old);}
 @PostMapping("/products/{id}/publish") public ApiResponse<?> publish(@PathVariable Long id){return change(id,true);}@PostMapping("/products/{id}/unpublish") public ApiResponse<?> unpublish(@PathVariable Long id){return change(id,false);}private ApiResponse<?> change(Long id,boolean v){Product p=DATA.get(id);if(p==null)throw new BizException(ErrorCodes.NOT_FOUND,"商品不存在",404);p.published=v;return ApiResponse.ok(p);}
 public static class Product{public Long id;@NotBlank public String name;public String price;public boolean published;public Product(){}Product(Long i,String n,String p,boolean s){id=i;name=n;price=new BigDecimal(p).setScale(2).toString();published=s;}}
 public static class Category{public Long id;public Long parentId;@NotBlank public String name;public int sortNo;}
}
