package com.cloudmall.product;

import com.cloudmall.common.api.ApiResponse;
import com.cloudmall.common.api.PageResult;
import com.cloudmall.common.auth.AuthContext;
import com.cloudmall.common.error.BizException;
import com.cloudmall.common.error.ErrorCodes;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.transaction.annotation.Transactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;
import javax.validation.Valid;
import javax.validation.constraints.NotBlank;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.*;
import java.time.Duration;

@RestController @RequestMapping("/api")
public class ProductController {
    private static final Logger log = LoggerFactory.getLogger(ProductController.class);
    private final JdbcTemplate db; private final RabbitTemplate rabbit; private final StringRedisTemplate redis; private final ObjectMapper objectMapper;
    public ProductController(JdbcTemplate db, RabbitTemplate rabbit, StringRedisTemplate redis, ObjectMapper objectMapper){this.db=db;this.rabbit=rabbit;this.redis=redis;this.objectMapper=objectMapper;}
    @GetMapping("/categories") public ApiResponse<?> categories(@RequestParam(required=false)Long parentId,@RequestParam(required=false)Integer status){StringBuilder s=new StringBuilder("select id,parent_id,name,sort_no,status from product_category where 1=1");List<Object>a=new ArrayList<>();if(parentId!=null){s.append(" and parent_id=?");a.add(parentId);}if(status!=null){s.append(" and status=?");a.add(status);}s.append(" order by sort_no,id");return ApiResponse.ok(db.query(s.toString(),a.toArray(),(r,n)->new Category(r.getLong("id"),r.getLong("parent_id"),r.getString("name"),r.getInt("sort_no"),r.getInt("status"))));}
    @Transactional @PostMapping("/categories") public ApiResponse<?> addCategory(@RequestBody Category c){AuthContext.requireAdmin();validateCategory(c);long id=id();db.update("insert into product_category(id,parent_id,name,sort_no,status,created_at,updated_at) values(?,?,?,?,1,?,?)",id,c.parentId,c.name,c.sortNo,now(),now());c.id=id;c.status=1;event("CATEGORY_CHANGED",id);return ApiResponse.ok(c);}
    @Transactional @PutMapping("/categories/{id}") public ApiResponse<?> updateCategory(@PathVariable Long id,@RequestBody Category c){AuthContext.requireAdmin();validateCategory(c);requireCategory(id);db.update("update product_category set parent_id=?,name=?,sort_no=?,updated_at=? where id=?",c.parentId,c.name,c.sortNo,now(),id);c.id=id;c.status=1;event("CATEGORY_CHANGED",id);return ApiResponse.ok(c);}
    @Transactional @DeleteMapping("/categories/{id}") public ApiResponse<?> deleteCategory(@PathVariable Long id){AuthContext.requireAdmin();requireCategory(id);db.update("update product_category set status=0,updated_at=? where id=?",now(),id);event("CATEGORY_CHANGED",id);return ApiResponse.ok(null);}
    @GetMapping("/products") public ApiResponse<?> products(@RequestParam(required=false)String keyword,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Integer status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize,@RequestParam(required=false)String sort){page=Math.max(1,page);pageSize=Math.min(Math.max(1,pageSize),100);StringBuilder w=new StringBuilder(" where 1=1");List<Object>a=new ArrayList<>();if(keyword!=null&&!keyword.isBlank()){w.append(" and name like ?");a.add("%"+keyword+"%");}if(categoryId!=null){w.append(" and category_id=?");a.add(categoryId);}if(status!=null){w.append(" and status=?");a.add(status);}long total=db.queryForObject("select count(*) from product"+w,a.toArray(),Long.class);List<Object>pa=new ArrayList<>(a);pa.add((page-1)*pageSize);pa.add(pageSize);List<Product> items=db.query("select id,category_id,name,main_image,description,price,status from product"+w+" order by updated_at desc,id desc limit ?,?",pa.toArray(),(r,n)->read(r.getLong("id"),r.getLong("category_id"),r.getString("name"),r.getString("main_image"),r.getString("description"),r.getBigDecimal("price"),r.getInt("status")));return ApiResponse.ok(new PageResult<>(items,page,pageSize,total));}
    @GetMapping("/products/{id}") public ApiResponse<?> product(@PathVariable Long id){return ApiResponse.ok(requireProduct(id));}
    @GetMapping("/products/skus/{skuId}") public ApiResponse<?> sku(@PathVariable Long skuId){List<Map<String,Object>>x=db.queryForList("select s.id sku_id,s.product_id,s.sku_code,s.spec_json,s.price,s.status,p.name,p.status product_status from product_sku s join product p on p.id=s.product_id where s.id=?",skuId);if(x.isEmpty())throw new BizException("PRODUCT_SKU_NOT_FOUND","SKU不存在",404);Map<String,Object>r=x.get(0);if(((Number)r.get("product_status")).intValue()!=1||((Number)r.get("status")).intValue()!=1)throw new BizException("PRODUCT_OFF_SHELF","商品已下架",409);return ApiResponse.ok(Map.of("skuId",r.get("sku_id"),"productId",r.get("product_id"),"productName",r.get("name"),"skuCode",r.get("sku_code"),"unitPrice",money((BigDecimal)r.get("price")),"skuSnapshot",readSpecJson(r.get("spec_json"))));}
    @GetMapping("/products/{id}/hot-stat") public ApiResponse<?> hot(@PathVariable Long id){requireProduct(id);List<HotStatResponse>x=db.query("select product_id,view_count,search_count,hot_score from product_hot_stat where product_id=?",(r,n)->new HotStatResponse(r.getLong("product_id"),r.getLong("view_count"),r.getLong("search_count"),r.getBigDecimal("hot_score")==null?"0.000000":r.getBigDecimal("hot_score").toPlainString()),id);return ApiResponse.ok(x.isEmpty()?new HotStatResponse(id,0,0,"0.000000"):x.get(0));}
    @Transactional @PostMapping("/products") public ApiResponse<?> create(@Valid@RequestBody Product p){AuthContext.requireAdmin();validateProduct(p);if(p.parameters==null)p.parameters=new ArrayList<>();long id=id();save(id,p);p.id=id;p.published=false;event("PRODUCT_CHANGED",id);return ApiResponse.ok(p);}
    @Transactional @PutMapping("/products/{id}") public ApiResponse<?> update(@PathVariable Long id,@RequestBody Product p){AuthContext.requireAdmin();validateProduct(p);requireProduct(id);db.update("update product set category_id=?,name=?,main_image=?,description=?,price=?,updated_at=? where id=?",p.categoryId,p.name,p.mainImage,p.description,money(p.price),now(),id);if(p.skus!=null)replaceSkus(id,p.skus);if(p.parameters!=null)replaceParameters(id,p.parameters);Product saved=requireProduct(id);event("PRODUCT_CHANGED",id);return ApiResponse.ok(saved);}
    @Transactional @PostMapping("/products/{id}/publish")public ApiResponse<?> publish(@PathVariable Long id){AuthContext.requireAdmin();return change(id,1);}
    @Transactional @PostMapping("/products/{id}/unpublish")public ApiResponse<?> unpublish(@PathVariable Long id){AuthContext.requireAdmin();return change(id,0);}
    @GetMapping("/seckill/activities/{id}") public ApiResponse<?> activity(@PathVariable Long id){return ApiResponse.ok(toActivityResponse(activityRecord(id)));}
    @PostMapping("/seckill/activities") public ApiResponse<?> createActivity(@RequestBody Activity a){AuthContext.requireAdmin();validateActivity(a);long id=id();db.update("insert into seckill_activity(id,sku_id,start_at,end_at,stock_limit,per_user_limit,status,created_at,updated_at) values(?,?,?,?,?,?, 'DRAFT',?,?)",id,a.skuId,ts(a.startAt),ts(a.endAt),a.stockLimit,a.perUserLimit,ts(now()),ts(now()));return activity(id);}
    @PutMapping("/seckill/activities/{id}") public ApiResponse<?> updateActivity(@PathVariable Long id,@RequestBody Activity a){AuthContext.requireAdmin();validateActivity(a);activity(id);db.update("update seckill_activity set sku_id=?,start_at=?,end_at=?,stock_limit=?,per_user_limit=?,updated_at=? where id=?",a.skuId,ts(a.startAt),ts(a.endAt),a.stockLimit,a.perUserLimit,ts(now()),id);return activity(id);}
    @PostMapping("/seckill/activities/{id}/publish") public ApiResponse<?> publishActivity(@PathVariable Long id){AuthContext.requireAdmin();ActivityRecord a=activityRecord(id);db.update("update seckill_activity set status='PUBLISHED',updated_at=? where id=?",ts(now()),id);String suffix=id+":"+a.skuId;Duration ttl=Duration.ofSeconds(Math.max(1,secondsUntil(a.endAt)));redis.opsForValue().set("seckill:stock:"+suffix,String.valueOf(a.stockLimit),ttl);redis.opsForValue().set("seckill:product:"+suffix,String.valueOf(toActivityResponse(a)),ttl);redis.opsForHash().put("seckill:meta:"+suffix,"perUserLimit",String.valueOf(a.perUserLimit));redis.opsForHash().put("seckill:meta:"+suffix,"stockLimit",String.valueOf(a.stockLimit));redis.opsForHash().put("seckill:meta:"+suffix,"startAt",toOffset(a.startAt).toInstant().toString());redis.opsForHash().put("seckill:meta:"+suffix,"endAt",toOffset(a.endAt).toInstant().toString());redis.expire("seckill:meta:"+suffix,ttl);return activity(id);}
    @PostMapping("/seckill/activities/{id}/start") public ApiResponse<?> startActivity(@PathVariable Long id){AuthContext.requireAdmin();activityRecord(id);db.update("update seckill_activity set status='STARTED',updated_at=? where id=?",ts(now()),id);return activity(id);}
    private ApiResponse<?> change(Long id,int st){Product p=requireProduct(id);db.update("update product set status=?,updated_at=? where id=?",st,now(),id);p.status=st;p.published=st==1;event("PRODUCT_CHANGED",id);return ApiResponse.ok(p);}
    private Product requireProduct(Long id){List<Product>x=db.query("select id,category_id,name,main_image,description,price,status from product where id=?",(r,n)->read(r.getLong("id"),r.getLong("category_id"),r.getString("name"),r.getString("main_image"),r.getString("description"),r.getBigDecimal("price"),r.getInt("status")),id);if(x.isEmpty())throw new BizException(ErrorCodes.NOT_FOUND,"商品不存在",404);return x.get(0);}
    private void requireCategory(Long id){if(db.queryForObject("select count(*) from product_category where id=?",Long.class,id)==0)throw new BizException(ErrorCodes.NOT_FOUND,"分类不存在",404);}
    private Product read(long id,long cat,String n,String image,String desc,BigDecimal price,int st){Product p=new Product();p.id=id;p.categoryId=cat;p.name=n;p.mainImage=image;p.description=desc;p.price=money(price);p.status=st;p.published=st==1;p.skus=db.query("select id,product_id,sku_code,spec_json,price,status from product_sku where product_id=? order by id",(r,z)->new Sku(r.getLong("id"),r.getLong("product_id"),r.getString("sku_code"),readSpecJson(r.getString("spec_json")),money(r.getBigDecimal("price")),r.getInt("status")==1),id);p.parameters=db.query("select id,product_id,param_name,param_value,sort_no from product_parameter where product_id=? order by sort_no,id",(r,z)->new ProductParameter(r.getLong("id"),r.getLong("product_id"),r.getString("param_name"),r.getString("param_value"),r.getInt("sort_no")),id);return p;}
    private void save(long id,Product p){db.update("insert into product(id,category_id,name,main_image,description,price,status,version,created_at,updated_at) values(?,?,?,?,?,?,0,0,?,?)",id,p.categoryId,p.name,p.mainImage,p.description,money(p.price),now(),now());replaceSkus(id,p.skus==null?List.of():p.skus);replaceParameters(id,p.parameters==null?List.of():p.parameters);}
    private void replaceSkus(long pid,List<Sku>ss){for(Sku s:ss){if(s==null)throw new BizException(ErrorCodes.INVALID,"SKU参数无效",400);if(s.id==null)s.id=id();db.update("insert into product_sku(id,product_id,sku_code,spec_json,price,status,created_at,updated_at) values(?,?,?,?,?,1,?,?) on duplicate key update price=values(price),spec_json=values(spec_json),status=values(status),updated_at=values(updated_at)",s.id,pid,s.skuCode,writeSpecJson(s.specJson),money(s.price),now(),now());}}
    private void replaceParameters(long pid,List<ProductParameter>ps){for(ProductParameter p:ps){if(p==null||p.name==null||p.name.isBlank()||p.value==null)throw new BizException(ErrorCodes.INVALID,"商品参数无效",400);}db.update("delete from product_parameter where product_id=?",pid);for(ProductParameter p:ps)db.update("insert into product_parameter(id,product_id,param_name,param_value,sort_no,created_at,updated_at) values(?,?,?,?,?,?,?)",id(),pid,p.name,p.value,p.sortNo,now(),now());}
    private int readStatus(long id){return requireProduct(id).status;}
    private void event(String type,long id){try{rabbit.convertAndSend("cloudmall.product.exchange","product.changed",eventEnvelope(type,id));}catch(Exception e){log.error("商品事件发送失败，事件类型={}，商品/分类ID={}；事务将回滚，Rabbit 消费端重试/DLX继续负责消费失败处理",type,id,e);throw new ProductEventPublishException(type,id,e);}}
    static final class ProductEventPublishException extends RuntimeException { ProductEventPublishException(String type,long id,Exception cause){super("商品事件发送失败，事件类型="+type+"，商品/分类ID="+id,cause);} }
    static Map<String,Object> eventEnvelope(String type,long id){
        String entityType=type.startsWith("CATEGORY")?"CATEGORY":"PRODUCT";
        String businessKeyName="CATEGORY".equals(entityType)?"categoryId":"productId";
        OffsetDateTime occurredAt=now();
        String eventId=UUID.randomUUID().toString();
        Map<String,Object> payload=Map.of(businessKeyName,id);
        return Map.of("eventId",eventId,"eventType",type,
                "occurredAt",occurredAt.toString(),"businessKey",Map.of("name",businessKeyName,"value",id),
                businessKeyName,id,"traceId",traceId(eventId),"payload",payload);
    }
    private static String traceId(String eventId){
        for(String key:List.of("traceId","trace_id","X-B3-TraceId")){
            String value=MDC.get(key);
            if(value!=null&&!value.isBlank())return value;
        }
        return "cloudmall-product-"+eventId;
    }
    private String writeSpecJson(Map<String,String> specJson){try{return objectMapper.writeValueAsString(specJson==null?Collections.emptyMap():specJson);}catch(JsonProcessingException e){throw new BizException(ErrorCodes.INVALID,"SKU规格格式错误",400);}}
    private Map<String,String> readSpecJson(Object value){try{JsonNode node=objectMapper.readTree(value==null?"{}":String.valueOf(value));if(!node.isObject())throw new BizException(ErrorCodes.INVALID,"SKU规格格式错误",400);Iterator<Map.Entry<String,JsonNode>> fields=node.fields();while(fields.hasNext())if(!fields.next().getValue().isTextual())throw new BizException(ErrorCodes.INVALID,"SKU规格格式错误",400);return objectMapper.convertValue(node,new TypeReference<LinkedHashMap<String,String>>(){});}catch(JsonProcessingException|IllegalArgumentException e){throw new BizException(ErrorCodes.INVALID,"SKU规格格式错误",400);}}
    private static OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.ofHours(8));}private static java.sql.Timestamp ts(OffsetDateTime x){return java.sql.Timestamp.from(x.toInstant());}private static long id(){return Math.abs(UUID.randomUUID().getMostSignificantBits());}private static String money(String x){try{return new BigDecimal(x==null?"0":x).setScale(2).toPlainString();}catch(Exception e){throw new BizException(ErrorCodes.INVALID,"金额格式错误",400);}}private static String money(BigDecimal x){return x.setScale(2).toPlainString();}
    private static long secondsUntil(Object value){if(value instanceof java.sql.Timestamp t)return Math.max(1,Duration.between(now(),t.toInstant().atOffset(ZoneOffset.ofHours(8))).getSeconds());try{return Math.max(1,Duration.between(now(),OffsetDateTime.parse(String.valueOf(value))).getSeconds());}catch(Exception e){return 1;}}
    private ActivityRecord activityRecord(Long id){List<ActivityRecord>x=db.query("select id,sku_id,start_at,end_at,stock_limit,per_user_limit,status from seckill_activity where id=?",(r,n)->new ActivityRecord(r.getLong("id"),r.getLong("sku_id"),r.getTimestamp("start_at"),r.getTimestamp("end_at"),r.getInt("stock_limit"),r.getInt("per_user_limit"),r.getString("status")),id);if(x.isEmpty())throw new BizException(ErrorCodes.NOT_FOUND,"秒杀活动不存在",404);return x.get(0);}
    private ActivityResponse toActivityResponse(ActivityRecord a){
        String stock=redis.opsForValue().get("seckill:stock:"+a.id+":"+a.skuId);
        return new ActivityResponse(a.id,a.skuId,toOffset(a.startAt),toOffset(a.endAt),
                resolveRemainingStock(stock,a.status,toOffset(a.endAt),now()),a.perUserLimit,a.status);
    }
    static int resolveRemainingStock(String redisValue,String status,OffsetDateTime endAt,OffsetDateTime currentTime){
        if(endAt==null||!endAt.isAfter(currentTime)||"ENDED".equals(status)||"CLOSED".equals(status))return 0;
        if(redisValue==null)return 0;
        try{return Math.max(0,Integer.parseInt(redisValue));}catch(NumberFormatException e){return 0;}
    }
    private static OffsetDateTime toOffset(java.sql.Timestamp value){return value.toInstant().atOffset(ZoneOffset.ofHours(8));}
    private static void validateCategory(Category c){if(c==null||c.name==null||c.name.isBlank())throw new BizException(ErrorCodes.INVALID,"分类名称不能为空",400);if(c.parentId==null)c.parentId=0L;}private static void validateProduct(Product p){if(p==null||p.name==null||p.name.isBlank())throw new BizException(ErrorCodes.INVALID,"商品名称不能为空",400);money(p.price);if(p.categoryId==null)p.categoryId=0L;}
    private static void validateActivity(Activity a){if(a==null||a.skuId==null||a.startAt==null||a.endAt==null||!a.endAt.isAfter(a.startAt)||a.stockLimit<1||a.perUserLimit<1)throw new BizException(ErrorCodes.INVALID,"秒杀活动参数无效",400);}
    public static class Product{@JsonSerialize(using=ToStringSerializer.class) public Long id;public Long categoryId=0L;@NotBlank public String name;public String mainImage,description,price;public boolean published;public int status;public List<Sku>skus=new ArrayList<>();public List<ProductParameter>parameters;}public static class Sku{public Long id;@JsonSerialize(using=ToStringSerializer.class) public Long productId;public String skuCode,price;public Map<String,String>specJson=new LinkedHashMap<>();public boolean status;public Sku(){}Sku(Long i,Long p,String c,Map<String,String>j,String v,boolean s){id=i;productId=p;skuCode=c;specJson=j;price=v;status=s;}}public static class ProductParameter{public Long id;@JsonSerialize(using=ToStringSerializer.class) public Long productId;public String name,value;public int sortNo;public ProductParameter(){}ProductParameter(Long i,Long p,String n,String v,int s){id=i;productId=p;name=n;value=v;sortNo=s;}}public static class Category{public Long id,parentId=0L;@NotBlank public String name;public int sortNo,status;Category(){}Category(long i,long p,String n,int s,int st){id=i;parentId=p;name=n;sortNo=s;status=st;}}public static class Activity{public Long skuId;public OffsetDateTime startAt,endAt;public int stockLimit,perUserLimit;}private record ActivityRecord(long id,long skuId,java.sql.Timestamp startAt,java.sql.Timestamp endAt,int stockLimit,int perUserLimit,String status){}public static class ActivityResponse{public final long activityId,skuId;public final OffsetDateTime startAt,endAt;public final int remainingStock,perUserLimit;public final String status;ActivityResponse(long a,long s,OffsetDateTime st,OffsetDateTime e,int r,int p,String v){activityId=a;skuId=s;startAt=st;endAt=e;remainingStock=r;perUserLimit=p;status=v;}}public static class HotStatResponse{public final long productId,viewCount,searchCount;public final String hotScore;HotStatResponse(long p,long v,long s,String h){productId=p;viewCount=v;searchCount=s;hotScore=h;}}
}
