server: {port: 8082}
spring:
  application: {name: cloud-mall-product}
  datasource: {url: "jdbc:mysql://localhost:13307/cloudmall_product?serverTimezone=Asia/Shanghai", username: root, password: root}
  redis: {host: 127.0.0.1, port: 16379, password: root, timeout: 2s}
  rabbitmq: {host: localhost, port: 15673, username: root, password: root}
  jackson.time-zone: Asia/Shanghai
management.endpoints.web.exposure.include: health,info,prometheus
spring.cloud.nacos.discovery.server-addr: localhost:8848
spring.cloud.nacos.discovery.username: root
spring.cloud.nacos.discovery.password: root
cloudmall:
  product:
    elasticsearch:
      url: http://localhost:9200
      index: cloudmall_product
