package com.cloudmall.user;
import com.cloudmall.common.api.ApiResponse; import com.cloudmall.common.auth.AuthContext; import com.cloudmall.common.error.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.web.bind.annotation.*; import javax.validation.Valid; import javax.validation.constraints.*; import java.util.*; import java.util.concurrent.*;
@RestController @RequestMapping("/api") public class UserController{
 static final BCryptPasswordEncoder ENC=new BCryptPasswordEncoder(); static final Map<String,User> USERS=new ConcurrentHashMap<>(); static final Map<String,User> TOKENS=new ConcurrentHashMap<>(); static{USERS.put("admin",new User(1L,"admin",ENC.encode("admin"),"ADMIN"));}
 @PostMapping("/auth/register") public ApiResponse<?> register(@Valid @RequestBody Credentials c){if(USERS.containsKey(c.username))throw new BizException("USER_DUPLICATE_USERNAME","用户名已存在",409); User u=new User((long)(USERS.size()+1),c.username,ENC.encode(c.password),"USER");USERS.put(c.username,u);return ApiResponse.ok(Map.of("userId",u.id,"username",u.username));}
 @PostMapping("/auth/login") public ApiResponse<?> login(@Valid @RequestBody Credentials c){User u=USERS.get(c.username);if(u==null||!ENC.matches(c.password,u.password))throw new BizException("USER_LOGIN_FAILED","用户名或密码错误",401);String t=UUID.randomUUID().toString();TOKENS.put(t,u);return ApiResponse.ok(Map.of("token",t,"user",Map.of("userId",u.id,"username",u.username,"role",u.role)));}
 @PostMapping("/auth/logout") public ApiResponse<?> logout(@RequestHeader(value="Authorization",required=false)String h){if(h!=null)TOKENS.remove(h.replace("Bearer ",""));return ApiResponse.ok(null);}
 @GetMapping("/users/me") public ApiResponse<?> me(){User u=current();return ApiResponse.ok(u.view());}
 @PutMapping("/users/me") public ApiResponse<?> update(@RequestBody Map<String,String> b){User u=current();u.nickname=b.getOrDefault("nickname",u.nickname);u.phone=b.getOrDefault("phone",u.phone);u.avatarUrl=b.getOrDefault("avatarUrl",u.avatarUrl);return ApiResponse.ok(u.view());}
 @GetMapping("/users/me/addresses") public ApiResponse<?> addresses(){return ApiResponse.ok(Collections.emptyList());}
 private User current(){org.springframework.web.context.request.ServletRequestAttributes a=(org.springframework.web.context.request.ServletRequestAttributes)org.springframework.web.context.request.RequestContextHolder.getRequestAttributes();String h=a==null?null:a.getRequest().getHeader("Authorization");String token=h==null?null:h.replace("Bearer ","");User u=token==null?null:TOKENS.get(token);if(u==null&&AuthContext.userId()!=null)for(User x:USERS.values())if(x.id.equals(AuthContext.userId()))u=x;if(u==null)throw new BizException(ErrorCodes.UNAUTHORIZED,"请先登录",401);return u;}
 static class Credentials{@NotBlank public String username;@NotBlank public String password;}
 static class User{Long id;String username,password,role,nickname="",phone="",avatarUrl="";User(Long i,String u,String p,String r){id=i;username=u;password=p;role=r;}Map<String,Object> view(){return Map.of("userId",id,"username",username,"role",role,"nickname",nickname,"phone",phone,"avatarUrl",avatarUrl);}}
}
