server: {port: 8085}
spring:
  application: {name: cloud-mall-stock}
  data.redis: {host: localhost, port: 6379, password: root, timeout: 2s}
  rabbitmq: {host: localhost, port: 5672, username: root, password: root}
management.endpoints.web.exposure.include: health,info,prometheus
spring.cloud.nacos.discovery.server-addr: localhost:8848
spring.cloud.nacos.discovery.username: root
spring.cloud.nacos.discovery.password: root
