server: {port: 8081}
spring:
  application: {name: cloud-mall-user}
  data.redis: {host: localhost, port: 6379, password: root, timeout: 2s}
  jackson.time-zone: Asia/Shanghai
management.endpoints.web.exposure.include: health,info,prometheus
spring.cloud.nacos.discovery.server-addr: localhost:8848
spring.cloud.nacos.discovery.username: root
spring.cloud.nacos.discovery.password: root
