import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api, Address, AddressRequest, CartItem, Order, User } from '../api'

const money = (value?: string | null) => `¥${Number(value || 0).toFixed(2)}`
const statusLabel: Record<string, string> = { PENDING_PAYMENT: '待付款', PAID: '已付款', COMPLETED: '已完成', CANCELLED: '已取消' }
const errorText = (e: unknown) => e instanceof Error ? e.message : '请求失败，请稍后重试'

export function ModernCartPage() {
  const navigate = useNavigate(); const [items, setItems] = useState<CartItem[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const load = () => { setLoading(true); api.cart().then(setItems).catch(e => setMessage(errorText(e))).finally(() => setLoading(false)) }
  useEffect(load, [])
  const selected = useMemo(() => items.filter(item => item.checked), [items]); const total = selected.reduce((sum, item) => sum + Number(item.unitPrice) * item.quantity, 0)
  const update = (item: CartItem, body: { quantity: number; checked?: boolean }) => api.updateCart(item.skuId, body).then(next => setItems(current => current.map(value => value.skuId === item.skuId ? next : value))).catch(e => setMessage(errorText(e)))
  const remove = (skuId: number) => api.removeCart(skuId).then(() => setItems(current => current.filter(item => item.skuId !== skuId))).catch(e => setMessage(errorText(e)))
  return <section className="commerce-page"><div className="commerce-heading"><div><span className="modern-kicker">YOUR BAG</span><h1>购物车</h1><p>确认想买的商品，下一步完成结算。</p></div><Link className="commerce-back" to="/products">继续逛逛 →</Link></div>{message && <div className="modern-alert">{message}</div>}{loading ? <div className="modern-loading">正在同步购物车…</div> : !items.length ? <div className="modern-empty">购物车还是空的，去挑几件喜欢的商品吧。</div> : <div className="commerce-layout"><div className="commerce-card"><div className="commerce-select-all"><input type="checkbox" checked={!!items.length && selected.length === items.length} onChange={event => Promise.all(items.map(item => update(item, { quantity: item.quantity, checked: event.target.checked }))).catch(() => {})} /> 全选</div>{items.map(item => <div className="commerce-cart-row" key={item.skuId}><input type="checkbox" checked={item.checked} onChange={event => update(item, { quantity: item.quantity, checked: event.target.checked })} /><div className="commerce-cart-main"><strong>{item.productName}</strong><small>{money(item.unitPrice)} / 件</small></div><div className="stepper"><button onClick={() => update(item, { quantity: Math.max(1, item.quantity - 1), checked: item.checked })}>−</button><span>{item.quantity}</span><button onClick={() => update(item, { quantity: item.quantity + 1, checked: item.checked })}>+</button></div><strong className="commerce-line-total">{money(String(Number(item.unitPrice) * item.quantity))}</strong><button className="commerce-remove" onClick={() => remove(item.skuId)}>删除</button></div>)}</div><aside className="commerce-summary"><span>已选 {selected.length} 件</span><strong>{money(String(total))}</strong><button className="modern-primary" disabled={!selected.length} onClick={() => api.preview({ skuIds: selected.map(item => item.skuId) }).then(() => navigate('/checkout')).catch(e => setMessage(errorText(e)))}>去结算</button></aside></div>}</section>
}

export function ModernCheckoutPage() {
  const navigate = useNavigate(); const [addresses, setAddresses] = useState<Address[]>([]); const [addressId, setAddressId] = useState(''); const [selected, setSelected] = useState<number[]>([]); const [preview, setPreview] = useState<import('../api').Settlement | null>(null); const [form, setForm] = useState<AddressRequest>({ receiver: '', phone: '', detailAddress: '', isDefault: false }); const [message, setMessage] = useState('')
  useEffect(() => { Promise.all([api.cart(), api.addresses()]).then(([cart, nextAddresses]) => { setSelected(cart.filter(item => item.checked).map(item => item.skuId)); setAddresses(nextAddresses); setAddressId(String(nextAddresses.find(item => item.isDefault)?.id || nextAddresses[0]?.id || '')) }).catch(e => setMessage(errorText(e))) }, [])
  const addAddress = (event: FormEvent) => { event.preventDefault(); api.addAddress(form).then(created => api.addresses().then(next => { setAddresses(next); setAddressId(String(created.id)); setForm({ receiver: '', phone: '', detailAddress: '', isDefault: false }) })).catch(e => setMessage(errorText(e))) }
  const previewOrder = () => api.preview({ skuIds: selected }).then(setPreview).catch(e => setMessage(errorText(e)))
  const submit = () => api.createOrder({ items: (preview?.items || []).map(item => ({ skuId: item.skuId, quantity: item.quantity })), addressId: Number(addressId) }).then(order => navigate(`/pay/${order.orderNo}`)).catch(e => setMessage(errorText(e)))
  return <section className="commerce-page"><div className="commerce-heading"><div><span className="modern-kicker">CHECKOUT</span><h1>确认订单</h1><p>地址、商品和金额都会在提交前再次校验。</p></div><Link className="commerce-back" to="/cart">返回购物车</Link></div>{message && <div className="modern-alert">{message}</div>}<div className="commerce-layout"><div><div className="commerce-card"><h2>收货地址</h2><select className="commerce-select" value={addressId} onChange={event => setAddressId(event.target.value)}><option value="">请选择收货地址</option>{addresses.map(address => <option key={address.id} value={address.id}>{address.receiver} · {address.phone} · {address.detailAddress}</option>)}</select><form className="commerce-address-form" onSubmit={addAddress}><input required placeholder="收货人" value={form.receiver} onChange={event => setForm({ ...form, receiver: event.target.value })} /><input required placeholder="联系电话" value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /><input required placeholder="详细地址" value={form.detailAddress} onChange={event => setForm({ ...form, detailAddress: event.target.value })} /><label><input type="checkbox" checked={form.isDefault} onChange={event => setForm({ ...form, isDefault: event.target.checked })} /> 设为默认地址</label><button className="commerce-secondary" type="submit">保存新地址</button></form></div><div className="commerce-card"><h2>商品与金额</h2><button className="commerce-secondary" disabled={!selected.length} onClick={previewOrder}>重新校验价格与库存</button>{preview && <><p>可结算商品：{preview.items.length} 件</p>{preview.invalidItems?.length ? <div className="modern-alert">有 {preview.invalidItems.length} 项商品已失效，请返回购物车调整。</div> : null}</>}</div></div><aside className="commerce-summary"><span>应付金额</span><strong>{money(preview?.payAmount || '0.00')}</strong><small>支付时将从账户余额扣除</small><button className="modern-primary" disabled={!preview || !addressId || !!preview.invalidItems?.length} onClick={submit}>提交订单</button></aside></div></section>
}

export function ModernOrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [filter, setFilter] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { api.orders({ page: 1, pageSize: 50 }).then(page => setOrders(page.items)).finally(() => setLoading(false)) }, [])
  const filtered = filter ? orders.filter(order => order.status === filter) : orders
  return <section className="commerce-page"><div className="commerce-heading"><div><span className="modern-kicker">ORDER CENTER</span><h1>我的订单</h1><p>查看订单状态和支付进度。</p></div><Link className="commerce-back" to="/products">继续购物 →</Link></div><div className="order-tabs"><button className={!filter ? 'active' : ''} onClick={() => setFilter('')}>全部</button>{Object.entries(statusLabel).map(([key, label]) => <button className={filter === key ? 'active' : ''} key={key} onClick={() => setFilter(key)}>{label}</button>)}</div>{loading ? <div className="modern-loading">订单加载中…</div> : !filtered.length ? <div className="modern-empty">暂无符合条件的订单</div> : <div className="commerce-card order-list">{filtered.map(order => <Link className="order-row" key={order.orderNo} to={`/orders/${order.orderNo}`}><div><strong>{order.orderNo}</strong><small>{new Date(order.createdAt).toLocaleString('zh-CN')}</small></div><span>{statusLabel[order.status] || order.status}</span><strong>{money(order.payAmount)}</strong></Link>)}</div>}</section>
}

export function ModernProfilePage() {
  const [user, setUser] = useState<User | null>(null); useEffect(() => { api.me().then(setUser).catch(() => setUser(null)) }, [])
  return <section className="commerce-page"><div className="commerce-heading"><div><span className="modern-kicker">ACCOUNT</span><h1>个人中心</h1><p>管理账户余额、收货地址和订单。</p></div></div><div className="account-grid"><div className="account-balance"><span>账户余额</span><strong>{money(user?.balance || '0.00')}</strong><small>余额支付可直接用于订单结算</small></div><Link className="account-entry" to="/orders"><b>我的订单</b><span>查看全部订单 →</span></Link><Link className="account-entry" to="/addresses"><b>收货地址</b><span>管理常用地址 →</span></Link></div></section>
}
