import { FormEvent, ReactNode, useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { api, Address, AddressRequest, AddressSnapshot, ApiError, auth, Category, Money, Product, ProductDetail, ProductParameter, ProductRequest, registerAndLogin, Sku, User } from './api'
import ModernHomePage from './pages/ModernHomePage'
import { CatalogPage } from './pages/CatalogPage'
import { ProductDetailPage } from './pages/ProductDetailPage'
import { ModernCartPage, ModernCheckoutPage, ModernOrdersPage, ModernProfilePage } from './pages/ModernCommercePages'
import ModernOrderDetailPage from './pages/ModernOrderDetailPage'
import ModernAdminProductsPage from './pages/ModernAdminProductsPage'

const money = (v?: Money | null) => `¥${Number(v || 0).toFixed(2)}`
export const resolveImageUrl = (value?: string | null) => {
  const source = value?.trim()
  if (!source) return ''
  if (source.startsWith('//')) return `${window.location.protocol}${source}`
  try { return new URL(source, window.location.origin).toString() } catch { return '' }
}
function ProductImage({src, alt, fallback = 'CM'}:{src?:string|null;alt:string;fallback?:string}) {
  const url = resolveImageUrl(src)
  return <div className="product-image">{url ? <img src={url} alt={alt} onError={e=>{e.currentTarget.hidden=true;e.currentTarget.parentElement?.classList.add('is-fallback')}}/> : null}<span className="image-fallback">{fallback}</span></div>
}
export const formatAddressSnapshot = (snapshot: AddressSnapshot) => {
  if (!snapshot) return '未提供地址快照'
  if (typeof snapshot !== 'string') return [snapshot.receiver, snapshot.phone, snapshot.detailAddress].filter(Boolean).join(' · ')
  try {
    const parsed = JSON.parse(snapshot) as Partial<Address>
    return [parsed.receiver, parsed.phone, parsed.detailAddress].filter(Boolean).join(' · ') || snapshot
  } catch { return snapshot }
}
const errorText = (e: unknown) => e instanceof ApiError ? `${e.message}（${e.code}）` : '网关暂不可用'
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value)
const emptyProductForm = (): ProductRequest => ({name:'',price:'0.00',categoryId:0,mainImage:'',description:'',parameters:[],skus:[]})
export const productDetailToForm = (product: ProductDetail): ProductRequest => ({
  name: product.name,
  price: String(product.price),
  categoryId: product.categoryId,
  mainImage: product.mainImage || '',
  description: product.description || '',
  parameters: (product.parameters || []).map(({name, value}: ProductParameter) => ({name: String(name), value: String(value)})),
  skus: (product.skus || []).map((sku: Sku) => ({
    ...(sku.id === undefined ? {} : {id: sku.id}),
    skuCode: String(sku.skuCode),
    specJson: Object.fromEntries(Object.entries(sku.specJson || {}).map(([key, value]) => [String(key), String(value)])),
    price: String(sku.price),
    status: Boolean(sku.status),
  })),
})
const parseJsonObject = (value: unknown, label: string): Record<string, string> => {
  if (typeof value !== 'string') throw new Error(`${label}必须是 JSON 对象`)
  const parsed: unknown = JSON.parse(value || '{}')
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error(`${label}必须是 JSON 对象`)
  return Object.fromEntries(Object.entries(parsed).map(([key, item]) => [String(key), String(item)]))
}
export const productFormToRequest = (form: ProductRequest, parametersText: string, skusText: string): ProductRequest => {
  const parameters: unknown = JSON.parse(parametersText || '[]')
  const skus: unknown = JSON.parse(skusText || '[]')
  if (!Array.isArray(parameters) || parameters.some(item => !isRecord(item) || typeof item.name !== 'string' || typeof item.value !== 'string')) throw new Error('商品参数必须是 [{name:string,value:string}]')
  if (!Array.isArray(skus)) throw new Error('SKU 必须是 JSON 数组')
  return {
    ...form,
    parameters: parameters as ProductParameter[],
    skus: skus.map((item: unknown) => {
      if (!isRecord(item) || typeof item.skuCode !== 'string' || typeof item.price !== 'string' || typeof item.status !== 'boolean' || !('specJson' in item)) throw new Error('SKU 字段不完整')
      const sku = item
      return { ...(sku.id === undefined ? {} : {id: Number(sku.id)}), skuCode: sku.skuCode as string, specJson: parseJsonObject(JSON.stringify(sku.specJson), 'SKU specJson'), price: sku.price as string, status: sku.status as boolean }
    }),
  }
}
function useLoad<T>(loader: () => Promise<T>, initial: T, dependencies: unknown[] = []) { const [data,setData]=useState(initial); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); useEffect(()=>{setLoading(true);setError('');loader().then(setData).catch(e=>setError(errorText(e))).finally(()=>setLoading(false))},dependencies); return {data,error,loading,setData} }
function Feedback({error}:{error?:string}) { return error ? <div className="alert">{error}</div> : null }
function Layout({children}:{children:ReactNode}) { const nav=useNavigate(); const [user,setUser]=useState<User|null>(null); useEffect(()=>{if(auth.get()) api.me().then(setUser).catch(()=>setUser(null)); const f=()=>{setUser(null);nav('/login')}; addEventListener('auth-expired',f); return()=>removeEventListener('auth-expired',f)},[nav]); return <><header><Link className="brand" to="/">Cloud<span>Mall</span></Link><nav><Link to="/products">商品</Link><Link to="/cart">购物车</Link><Link to="/orders">我的订单</Link>{user?.roles.includes('ADMIN')&&<Link to="/admin/products">管理台</Link>}</nav><div className="account">{user?<><Link to="/profile">{user.nickname||user.username}</Link><button className="link" onClick={()=>api.logout().catch(()=>{}).finally(()=>{auth.clear();setUser(null);nav('/login')})}>退出</button></>:<Link to="/login">登录</Link>}</div></header><main>{children}</main><footer>CloudMall 云购微商城 · 学习型微服务电商项目</footer></> }
function Home(){return <div className="hero"><div><p className="eyebrow">CLOUDMALL / 云购微商城</p><h1>把好商品，<br/><em>放心放进购物车。</em></h1><p className="lead">从浏览、选购到支付完成，体验完整的微服务电商闭环。</p><Link className="button" to="/products">开始逛逛 →</Link></div><div className="hero-card"><span>本周精选</span><strong>发现你的<br/>下一件心头好</strong><Link to="/products">探索商品</Link></div></div>}
function Products(){const [params,setParams]=useSearchParams(); const [keyword,setKeyword]=useState(params.get('keyword')||''); const query={keyword:params.get('keyword')||undefined,categoryId:params.get('categoryId')?Number(params.get('categoryId')):undefined,status:1,page:1,pageSize:20}; const queryKey=params.toString(); const {data,error,loading}=useLoad(()=>api.products(query),{items:[],page:1,pageSize:20,total:0},[queryKey]); const cats=useLoad(()=>api.categories({status:1}),[] as Category[]); const search=(e:FormEvent)=>{e.preventDefault();window.location.href=keyword?`/products?keyword=${encodeURIComponent(keyword)}`:'/products'}; return <section className="page"><div className="page-heading"><div><p className="eyebrow">DISCOVER</p><h2>全部商品</h2></div><form onSubmit={search}><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="搜索商品名称"/><button className="button small">搜索</button></form></div><div className="chips"><Link className={!params.get('categoryId')?'selected':''} to="/products">全部</Link>{cats.data.map(c=><Link className={params.get('categoryId')===String(c.id)?'selected':''} key={c.id} to={`/products?categoryId=${c.id}`}>{c.name}</Link>)}</div><Feedback error={error||cats.error}/>{loading?<p>正在加载商品…</p>:<div className="grid">{data.items.map(p=><ProductCard key={p.id} product={p}/>)}</div>}{!loading&&!data.items.length&&!error&&<Empty text="暂无商品，请稍后再试"/>}</section>}
function ProductCard({product}:{product:Product}){return <Link className="product-card" to={`/products/${product.id}`}><ProductImage src={product.mainImage} alt={product.name}/><div className="product-info"><h3>{product.name}</h3><p>{money(product.price)}</p></div></Link>}
function ProductPage(){const {id=''}=useParams(); const {data,error,loading}=useLoad(()=>api.product(id),{} as ProductDetail); const [sku,setSku]=useState(''); const [quantity,setQuantity]=useState(1); const [message,setMessage]=useState(''); const nav=useNavigate(); if(loading)return <section className="page"><p>正在加载商品详情…</p></section>; return <section className="page"><Feedback error={error||message}/>{!error&&<div className="detail"><div className="detail-image"><ProductImage src={data.mainImage} alt={data.name} fallback="CloudMall"/></div><div><p className="eyebrow">PRODUCT DETAIL</p><h2>{data.name}</h2><div className="price">{money(data.skus?.find(s=>String(s.id)===sku)?.price||data.price)}</div><p>{data.description||'精选商品，服务端价格与库存以结算校验为准。'}</p>{data.skus?.length>0&&<><h4>选择规格</h4><div className="chips">{data.skus.filter(s=>s.status).map(s=><button className={sku===String(s.id)?'selected':''} key={s.id} onClick={()=>setSku(String(s.id))}>{Object.values(s.specJson||{}).join(' / ')||s.skuCode}</button>)}</div></>}<input className="qty" type="number" min="1" value={quantity} onChange={e=>setQuantity(Math.max(1,Number(e.target.value)||1))}/><button className="button" disabled={!sku} onClick={()=>api.addCart({skuId:Number(sku),quantity}).then(()=>nav('/cart')).catch(e=>setMessage(errorText(e)))}>加入购物车</button></div></div>}</section>}
function Auth({register=false}:{register?:boolean}){const [form,setForm]=useState({username:'',password:''}); const [message,setMessage]=useState(''); const nav=useNavigate(); const submit=(e:FormEvent)=>{e.preventDefault();(register?registerAndLogin(form):api.login(form)).then(v=>{auth.set(v.token);nav('/')}).catch(e=>setMessage(errorText(e)))}; return <section className="auth"><div className="auth-panel"><p className="eyebrow">WELCOME TO CLOUDMALL</p><h2>{register?'创建账户':'欢迎回来'}</h2><Feedback error={message}/><form onSubmit={submit}><input required placeholder="用户名" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input required minLength={6} type="password" placeholder="密码（至少 6 位）" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="button">{register?'注册':'登录'}</button></form><p>{register?'已有账号？':'还没有账号？'} <Link to={register?'/login':'/register'}>{register?'立即登录':'注册账号'}</Link></p></div></section>}
function RequireAuth({children,admin=false}:{children:ReactNode;admin?:boolean}){const [ok,setOk]=useState<boolean|null>(null); useEffect(()=>{api.me().then(u=>setOk(!admin||u.roles.includes('ADMIN'))).catch(()=>setOk(false))},[admin]); if(ok===null)return <section className="page"><p>正在验证登录态…</p></section>; return ok?<>{children}</>:<Navigate to="/login" replace/>}
function Cart(){const {data,error,loading,setData}=useLoad(api.cart,[] as import('./api').CartItem[]); const nav=useNavigate(); const [message,setMessage]=useState(''); const update=(skuId:number,body:import('./api').CartUpdateRequest)=>api.updateCart(skuId,body).then(item=>setData(data.map(x=>x.skuId===skuId?item:x))).catch(e=>setMessage(errorText(e))); const selected=data.filter(i=>i.checked); return <section className="page"><p className="eyebrow">YOUR BAG</p><h2>购物车</h2><Feedback error={error||message}/>{loading?<p>加载中…</p>:data.length?<><div className="list">{data.map(i=><div className="line" key={i.skuId}><input type="checkbox" checked={i.checked} onChange={e=>update(i.skuId,{quantity:i.quantity,checked:e.target.checked})}/><div><strong>{i.productName}</strong><small>{money(i.unitPrice)} × {i.quantity}</small></div><input className="qty" type="number" min="1" value={i.quantity} onChange={e=>update(i.skuId,{quantity:Math.max(1,Number(e.target.value)||1)})}/><button className="link" onClick={()=>api.removeCart(i.skuId).then(()=>setData(data.filter(x=>x.skuId!==i.skuId))).catch(e=>setMessage(errorText(e)))}>删除</button></div>)}</div><button className="button" disabled={!selected.length} onClick={()=>api.preview({skuIds:selected.map(i=>i.skuId)}).then(()=>nav('/checkout')).catch(e=>setMessage(errorText(e)))}>去结算（{selected.length}）</button></>:<Empty text="购物车还是空的"/>}</section>}
function Checkout(){const [addresses,setAddresses]=useState<Address[]>([]); const [selected,setSelected]=useState<number[]>([]); const [addressId,setAddressId]=useState(''); const [preview,setPreview]=useState<import('./api').Settlement|null>(null); const [message,setMessage]=useState(''); const [addressForm,setAddressForm]=useState<AddressRequest>({receiver:'',phone:'',detailAddress:'',isDefault:false}); const nav=useNavigate(); useEffect(()=>{Promise.all([api.cart(),api.addresses()]).then(([cart,as])=>{setSelected(cart.filter(x=>x.checked).map(x=>x.skuId));setAddresses(as);setAddressId(String(as.find(x=>x.isDefault)?.id||as[0]?.id||''))}).catch(e=>setMessage(errorText(e)))},[]); const loadPreview=()=>api.preview({skuIds:selected}).then(setPreview).catch(e=>setMessage(errorText(e))); const addAddress=(e:FormEvent)=>{e.preventDefault();api.addAddress(addressForm).then(created=>api.addresses().then(as=>{setAddresses(as);setAddressId(String(as.find(a=>a.id===created.id)?.id||created.id));setAddressForm({receiver:'',phone:'',detailAddress:'',isDefault:false})})).catch(e=>setMessage(errorText(e)))}; const create=()=>api.createOrder({items:(preview?.items||[]).map(x=>({skuId:x.skuId,quantity:x.quantity})),addressId:Number(addressId)}).then(o=>nav(`/pay/${o.orderNo}`)).catch(e=>setMessage(errorText(e))); return <section className="page narrow"><p className="eyebrow">CHECKOUT</p><h2>确认订单</h2><Feedback error={message}/><label htmlFor="checkout-address">收货地址</label><select id="checkout-address" value={addressId} onChange={e=>setAddressId(e.target.value)}><option value="">请选择收货地址</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.receiver} · {a.phone} · {a.detailAddress}</option>)}</select><form className="address-form" onSubmit={addAddress}><h3>新增收货地址</h3><input required placeholder="收货人" value={addressForm.receiver} onChange={e=>setAddressForm({...addressForm,receiver:e.target.value})}/><input required placeholder="联系电话" value={addressForm.phone} onChange={e=>setAddressForm({...addressForm,phone:e.target.value})}/><input required placeholder="详细地址" value={addressForm.detailAddress} onChange={e=>setAddressForm({...addressForm,detailAddress:e.target.value})}/><label><input type="checkbox" checked={addressForm.isDefault} onChange={e=>setAddressForm({...addressForm,isDefault:e.target.checked})}/> 设为默认地址</label><button className="button" type="submit">保存并使用此地址</button></form><button className="button ghost" disabled={!selected.length} onClick={loadPreview}>重新校验价格与库存</button>{preview&&<div className="card"><p>可结算商品：{preview.items.length} 件</p><p>应付金额：<span className="price">{money(preview.payAmount)}</span></p>{preview.invalidItems?.length?<Feedback error={`有 ${preview.invalidItems.length} 项商品失效，请返回购物车调整。`}/>:null}<button className="button" disabled={!addressId||!!preview.invalidItems?.length} onClick={create}>提交订单</button></div>}</section>}
function Orders(){const {data,error,loading}=useLoad(()=>api.orders({page:1,pageSize:20}),{items:[],page:1,pageSize:20,total:0}); return <section className="page"><p className="eyebrow">ORDER CENTER</p><h2>我的订单</h2><Feedback error={error}/>{loading?<p>加载中…</p>:data.items.map(o=><Link className="line order" key={o.orderNo} to={`/orders/${o.orderNo}`}><div><strong>{o.orderNo}</strong><small>{new Date(o.createdAt).toLocaleString('zh-CN')}</small></div><b>{o.status}</b><span>{money(o.payAmount)}</span></Link>)}{!loading&&!data.items.length&&!error&&<Empty text="还没有订单"/>}</section>}
function OrderDetailPage(){const {no=''}=useParams(); const {data,error,loading}=useLoad(()=>api.order(no),{} as import('./api').OrderDetail); const [message,setMessage]=useState(''); const action=(fn:()=>Promise<unknown>)=>fn().then(()=>location.reload()).catch(e=>setMessage(errorText(e))); if(loading)return <section className="page"><p>加载中…</p></section>; return <section className="page narrow"><Feedback error={error||message}/>{!error&&<><p className="eyebrow">ORDER {data.orderNo}</p><h2>{data.status}</h2><p>应付金额：<span className="price">{money(data.payAmount)}</span></p>{data.items?.map((i,n)=><div className="line" key={n}><span>{i.productNameSnapshot} × {i.quantity}</span><b>{money(i.lineAmount)}</b></div>)}<p>收货：{formatAddressSnapshot(data.addressSnapshot)}</p>{data.status==='PENDING_PAYMENT'&&<><button className="button" onClick={()=>action(()=>api.cancelOrder(data.orderNo,'用户取消'))}>取消订单</button><Link className="button ghost" to={`/pay/${data.orderNo}`}>去支付</Link></>}{data.status==='PAID'&&<button className="button" onClick={()=>action(()=>api.confirmOrder(data.orderNo))}>确认收货</button>}</>}</section>}
function Pay(){const {no=''}=useParams(); const [amount,setAmount]=useState(''); const [payNo,setPayNo]=useState(''); const [message,setMessage]=useState(''); useEffect(()=>{api.order(no).then(o=>setAmount(String(o.payAmount))).catch(e=>setMessage(errorText(e)))},[no]); const create=()=>api.createPayment({orderNo:no,payAmount:amount}).then(p=>setPayNo(p.payNo)).catch(e=>setMessage(errorText(e))); return <section className="page narrow"><p className="eyebrow">BALANCE PAYMENT</p><h2>余额支付</h2><p>订单：{no}</p><Feedback error={message}/><input value={amount} readOnly placeholder="应付金额（字符串）"/>{payNo?<><p>支付单：{payNo}</p><p>点击支付后将从账户余额中扣除订单金额，余额不足时支付失败。</p><button className="button" onClick={()=>api.mockSuccess(payNo).then(()=>location.href=`/pay-result/${no}`).catch(e=>setMessage(errorText(e)))}>使用余额支付</button><button className="button ghost" onClick={()=>api.mockFail(payNo,'用户取消支付').then(()=>location.href=`/pay-result/${no}`).catch(e=>setMessage(errorText(e)))}>取消支付</button></>:<button className="button" disabled={!amount} onClick={create}>确认支付</button>}</section>}
function PayResult(){const {no=''}=useParams(); const {data,error}=useLoad(()=>api.payment(no),{} as import('./api').Payment); return <section className="page narrow"><p className="eyebrow">PAYMENT RESULT</p><h2>{error?'支付状态暂不可用':data.status}</h2><p>{error||`订单 ${no} 的支付状态已从服务端读取。`}</p><Link className="button" to={`/orders/${no}`}>查看订单</Link></section>}
function Profile(){const {data,error,loading,setData}=useLoad(api.me,{} as User); const [message,setMessage]=useState(''); const [editing,setEditing]=useState(false); const [form,setForm]=useState({nickname:'',phone:'',avatarUrl:''}); useEffect(()=>{if(data.id)setForm({nickname:data.nickname||'',phone:data.phone||'',avatarUrl:data.avatarUrl||''})},[data]); const save=()=>api.updateMe(form).then(u=>{setData(u);setEditing(false)}).catch(e=>setMessage(errorText(e))); return <section className="page narrow"><p className="eyebrow">ACCOUNT</p><h2>个人信息</h2><Feedback error={error||message}/>{loading?<p>加载中…</p>:editing?<div className="card"><input placeholder="昵称" value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})}/><input placeholder="手机号" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="头像 URL" value={form.avatarUrl} onChange={e=>setForm({...form,avatarUrl:e.target.value})}/><button className="button" onClick={save}>保存</button></div>:<div className="card"><p>用户名：{data.username}</p><p>账户余额：<span className="price">{money(data.balance)}</span></p><p>昵称：{data.nickname||'未设置'}</p><p>角色：{data.roles?.join(', ')}</p><button className="button small" onClick={()=>setEditing(true)}>编辑资料</button><Link className="button small ghost" to="/addresses">管理收货地址</Link></div>}</section>}
function Addresses(){const {data,error,loading,setData}=useLoad(api.addresses,[] as Address[]); const empty={receiver:'',phone:'',detailAddress:'',isDefault:false}; const [form,setForm]=useState<AddressRequest>(empty); const [editing,setEditing]=useState<number|null>(null); const [message,setMessage]=useState(''); const save=()=>{const action=editing===null?api.addAddress(form):api.updateAddress(editing,form); action.then(a=>{setData(editing===null?[...data,a]:data.map(x=>x.id===a.id?a:x));setForm(empty);setEditing(null)}).catch(e=>setMessage(errorText(e)))}; return <section className="page narrow"><p className="eyebrow">DELIVERY</p><h2>收货地址</h2><Feedback error={error||message}/>{loading?<p>加载中…</p>:data.map(a=><div className="card" key={a.id}><strong>{a.receiver} · {a.phone}</strong><p>{a.detailAddress}</p>{a.isDefault&&<span className="tag">默认</span>}<button className="link" onClick={()=>{setEditing(a.id);setForm({receiver:a.receiver,phone:a.phone,detailAddress:a.detailAddress,isDefault:a.isDefault})}}>编辑</button> <button className="link" onClick={()=>api.deleteAddress(a.id).then(()=>setData(data.filter(x=>x.id!==a.id))).catch(e=>setMessage(errorText(e)))}>删除</button></div>)}<div className="card"><h3>{editing===null?'新增地址':'编辑地址'}</h3><input required placeholder="收货人" value={form.receiver} onChange={e=>setForm({...form,receiver:e.target.value})}/><input required placeholder="电话" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input required placeholder="详细地址" value={form.detailAddress} onChange={e=>setForm({...form,detailAddress:e.target.value})}/><label><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> 设为默认</label><button className="button" onClick={save}>保存地址</button></div></section>}
function AdminProducts(){
  const [editing,setEditing]=useState<number|string|null>(null); const [products,setProducts]=useState<Product[]>([]); const [form,setForm]=useState<ProductRequest>(emptyProductForm); const [parametersText,setParametersText]=useState('[]'); const [skusText,setSkusText]=useState('[]'); const [message,setMessage]=useState('')
  const load=()=>api.products({page:1,pageSize:50}).then(p=>setProducts(p.items)).catch(e=>setMessage(errorText(e))); useEffect(()=>{load()},[])
  const beginEdit=(product: Product)=>api.product(product.id).then(detail=>{const next=productDetailToForm(detail);setEditing(product.id);setForm(next);setParametersText(JSON.stringify(next.parameters || [], null, 2));setSkusText(JSON.stringify(next.skus || [], null, 2))}).catch(e=>setMessage(errorText(e)))
  const save=()=>{try { const body=productFormToRequest(form,parametersText,skusText); const fn=editing===null?api.createProduct(body):api.updateProduct(editing,body); fn.then(detail=>{productDetailToForm(detail);setEditing(null);setForm(emptyProductForm());setParametersText('[]');setSkusText('[]');setMessage('商品及 SKU/参数已保存');load()}).catch(e=>setMessage(errorText(e))) } catch (e) { setMessage(e instanceof Error?e.message:'商品数据格式不正确') }}
  return <section className="page"><p className="eyebrow">ADMIN CONSOLE</p><h2>商品管理</h2><Feedback error={message}/><div className="card admin-form"><h3>{editing===null?'新增商品':'编辑商品'}</h3><input placeholder="商品名称" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="价格（字符串）" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input type="number" placeholder="分类 ID" value={form.categoryId||''} onChange={e=>setForm({...form,categoryId:Number(e.target.value)})}/><input placeholder="主图 URL" value={form.mainImage||''} onChange={e=>setForm({...form,mainImage:e.target.value})}/><textarea placeholder="描述" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/><textarea aria-label="商品参数 JSON" placeholder='参数 JSON，例如 [{"name":"颜色","value":"黑色"}]' value={parametersText} onChange={e=>setParametersText(e.target.value)}/><textarea aria-label="SKU JSON" placeholder='SKU JSON，specJson 必须是对象' value={skusText} onChange={e=>setSkusText(e.target.value)}/><button className="button" onClick={save} disabled={!form.name||!form.categoryId}>保存商品</button></div><div className="list">{products.map(p=><div className="line" key={p.id}><div><strong>{p.name}</strong><small>{money(p.price)} · {p.status===1?'已上架':'未上架'}</small></div><button className="link" onClick={()=>beginEdit(p)}>编辑</button>{p.status===1?<button className="link" onClick={()=>api.unpublishProduct(p.id).then(load).catch(e=>setMessage(errorText(e)))}>下架</button>:<button className="link" onClick={()=>api.publishProduct(p.id).then(load).catch(e=>setMessage(errorText(e)))}>上架</button>}</div>)}</div></section>}
function AdminCategories(){const [items,setItems]=useState<Category[]>([]); const [form,setForm]=useState({name:'',parentId:0,sortNo:0}); const [editing,setEditing]=useState<number|null>(null); const [message,setMessage]=useState(''); const load=()=>api.categories().then(setItems).catch(e=>setMessage(errorText(e))); useEffect(()=>{load()},[]); const save=()=>{const fn=editing===null?api.createCategory(form):api.updateCategory(editing,form);fn.then(()=>{setEditing(null);setForm({name:'',parentId:0,sortNo:0});load()}).catch(e=>setMessage(errorText(e)))}; return <section className="page narrow"><p className="eyebrow">ADMIN CONSOLE</p><h2>分类管理</h2><Feedback error={message}/><div className="card"><input placeholder="分类名称" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="number" placeholder="父分类 ID" value={form.parentId} onChange={e=>setForm({...form,parentId:Number(e.target.value)})}/><input type="number" placeholder="排序号" value={form.sortNo} onChange={e=>setForm({...form,sortNo:Number(e.target.value)})}/><button className="button" onClick={save} disabled={!form.name}>保存分类</button></div><div className="list">{items.map(c=><div className="line" key={c.id}><div><strong>{c.name}</strong><small>ID {c.id} · {c.status===1?'启用':'停用'}</small></div><button className="link" onClick={()=>{setEditing(c.id);setForm({name:c.name,parentId:c.parentId,sortNo:c.sortNo})}}>编辑</button><button className="link" onClick={()=>api.deleteCategory(c.id).then(load).catch(e=>setMessage(errorText(e)))}>停用/删除</button></div>)}</div></section>}
function Seckill(){const {id=''}=useParams(); const {data,error,loading}=useLoad(()=>api.seckill(id),{} as import('./api').SeckillActivity); const [message,setMessage]=useState(''); const [now,setNow]=useState(Date.now()); useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]); const start=new Date(data.startAt||0).getTime(); const end=new Date(data.endAt||0).getTime(); const running=data.status==='RUNNING'||(start<=now&&now<end); const label=now<start?`${Math.ceil((start-now)/1000)} 秒后开始`:running?'进行中':'已结束'; return <section className="page narrow"><p className="eyebrow">LIMITED DROP</p><h2>限时秒杀</h2><Feedback error={error||message}/>{loading?<p>加载中…</p>:!error&&<><p>活动状态：<strong>{data.status||label}</strong>（{label}）</p><p>剩余展示库存：{data.remainingStock}</p><p>活动窗口：{data.startAt} 至 {data.endAt}</p><button className="button" disabled={!running} onClick={()=>api.seckillOrder({activityId:Number(id),skuId:data.skuId}).then(o=>{if(!o.orderNo) throw new ApiError('COMMON_INTERNAL_ERROR','秒杀响应缺少订单号',200); location.href=`/orders/${o.orderNo}`}).catch(e=>setMessage(errorText(e)))}>立即秒杀</button></>}</section>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
export default function App(){return <Layout><Routes><Route path="/" element={<ModernHomePage/>}/><Route path="/products" element={<CatalogPage/>}/><Route path="/products/:id" element={<ProductDetailPage/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth register/>}/><Route path="/cart" element={<RequireAuth><ModernCartPage/></RequireAuth>}/><Route path="/checkout" element={<RequireAuth><ModernCheckoutPage/></RequireAuth>}/><Route path="/orders" element={<RequireAuth><ModernOrdersPage/></RequireAuth>}/><Route path="/orders/:no" element={<RequireAuth><ModernOrderDetailPage/></RequireAuth>}/><Route path="/pay/:no" element={<RequireAuth><Pay/></RequireAuth>}/><Route path="/pay-result/:no" element={<RequireAuth><PayResult/></RequireAuth>}/><Route path="/seckill/:id" element={<RequireAuth><Seckill/></RequireAuth>}/><Route path="/profile" element={<RequireAuth><ModernProfilePage/></RequireAuth>}/><Route path="/addresses" element={<RequireAuth><Addresses/></RequireAuth>}/><Route path="/admin/products" element={<RequireAuth admin><ModernAdminProductsPage/></RequireAuth>}/><Route path="/admin/categories" element={<RequireAuth admin><AdminCategories/></RequireAuth>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Layout>}
